server {
    listen 443 ssl;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate_key P_KEY;
    ssl_certificate CERTS;

    root /var/www/html/wordpress;
    index index.php;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ 
    {
        include fastcgi_params; #include info abt request in fastcgi to send them to php-fpm

        fastcgi_index index.php;

        fastcgi_param SCRIPT_NAME $fastcgi_script_name; #The requested PHP script is /nada.php
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; #This tells PHP-FPM where the actual PHP file is located on the filesystem.

        fastcgi_pass wordpress:9000; #where to send request
    }
}